routes/admin.php
<?php

Route::get('/', ['as' => 'dashboard.index', 'uses' => 'DashboardController@getIndex']);
Route::post('admin/article/{id}', ['as' => 'admin.article.delete', 'uses' => 'ArticleController@destroy']);
Route::resource('article', 'ArticleController');
Route::resource('category', 'CategoryController');
Route::resource('page', 'PageController');
Route::resource('user', 'UserController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', ['as' => 'root', 'uses' => 'PageController@getIndex']);
Route::get('article/{articleSlug}', ['as' => 'article', 'uses' => 'PageController@getArticle']);
Route::get('news', ['as' => 'news', 'uses' => 'PageController@getAllArticlesCategory']);
// Route::get('page/{pSlug}', ['as' => 'page', 'uses' => 'PageController@getPage']);
Route::get('category/{categorySlug}', ['as' => 'category', 'uses' => 'PageController@getCategory']);
Route::get('sitemap.xml', ['as' => 'sitemap', 'uses' => 'PageController@getSitemap']);

app/Models/Article.php
<?php

namespace App\Models;

use App\Base\SluggableModel;
use DateTimeInterface;

class Article extends SluggableModel
{
    /**
     * Carbon instance fields
     *
     * @var array
     */
    protected $dates = ['published_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @param $query
     *
     * @return mixed
     */
    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now())->orderBy('published_at', 'desc');
    }

    /**
     * @return string
     */
    public function getLocalizedPublishedAtAttribute(): string
    {
        return $this->published_at->formatLocalized('%e %B %Y');
    }

    /**
     * Prepare a date for array / JSON serialization.
     *
     * @param  \DateTimeInterface  $date
     * @return string
     */
    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    /**
     * @return string
     */
    public function getLinkAttribute(): string
    {
        return route('article', ['articleSlug' => $this->slug]);
    }
}

app/Models/Page.php
<?php

namespace App\Models;

use App\Base\SluggableModel;
use DateTimeInterface;

class Page extends SluggableModel
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(__CLASS__);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(__CLASS__, 'parent_id', 'id');
    }

    /**
     * @return string
     */
    public function getLinkAttribute(): string
    {
        return route('page', ['pSlug' => $this->slug]);
    }

    /**
     * Prepare a date for array / JSON serialization.
     *
     * @param  \DateTimeInterface  $date
     * @return string
     */
    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

resources/views/partials/app/articles.blade.php
<section id="articles" class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 entries">
                @forelse ($articles as $article)
                    <article class="entry">
                        <div class="entry-img">
                            <img src="{{ $article->image }}" alt="" class="img-fluid">
                        </div>
                        <h2 class="entry-title">
                            <a href="{{ $article->link }}">{{ $article->title }}</a>
                        </h2>
                        <div class="entry-meta">
                            <ul>
                                <li class="d-flex align-items-center">
                                    <i class="icofont-wall-clock"></i>
                                    <a href="{{ $article->link }}">
                                        <time datetime="2020-01-01">{{ $article->localized_published_at }}</time>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="entry-content">
                            <p> {{ getNWords($article->content, 50) }} </p>
                            <div class="read-more">
                                <a href="{{ $article->link }}">Leer más</a>
                            </div>
                        </div>
                    </article>
                @empty
                    <article class="entry">
                        <h2 class="entry-title">
                            No hay noticias publicadas
                        </h2>
                    </article>
                @endforelse

                @if ($articles->total() > $articles->count())
                    <div class="col-md-12">
                        {!! $articles->appends(request()->except('page'))->links() !!}
                    </div>
                @endif
            </div>
            @include('partials.app.sidebar')
        </div>
    </div>
</section>

resources/views/partials/app/breadcrumbs.blade.php
<nav aria-label="breadcrumb">
  <ol class="breadcrumb transparent-bg center-flex">
    <li class="breadcrumb-item"><a href="{{ route('root') }}">{{ getTitle() }}</a></li>
    @if (isset($object->parent))
        <li class="breadcrumb-item"><a href="{{ $object->parent->link }}">{{ $object->parent->title }}</a></li>
    @elseif (isset($object->category))
        <li class="breadcrumb-item"><a href="{{ $object->category->link }}">{{ $object->category->title }}</a></li>
    @endif
    <li class="breadcrumb-item active" aria-current="page"><a href="{{ url()->current() }}}" aria-current="page">{{ $object->title }}</a></li>
  </ol>
</nav>

resources/views/partials/app/content.blade.php
<div id="blog-content" class="container mb-2">
   <div class="row">
      <div class="d-none d-lg-block d-xl-block col-lg-12 center-flex">
         <div class="jumbotron jumbotron-fluid hero-image" data-img="{{ $image }}">
            <div class="container">
               <h1 class="text-center display-4">{{$title}}</h1>
               @include('partials.app.breadcrumbs')
            </div>
         </div>
      </div>
      <section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
         <div class="container">
            <div class="row">
               <div class="col-lg-8 entries">
                  <article class="entry entry-single">
                     <div class="d-lg-none d-xl-none entry-img">
                        <img src="{{ $image }}" alt="" class="img-fluid">
                     </div>
                     <h2 class="d-lg-none d-xl-none entry-title">
                        <a href="blog-single.html">{{$title}}</a>
                     </h2>
                     <div class="d-lg-none d-xl-none entry-meta">
                        @include('partials.app.breadcrumbs')
                     </div>
                     <div class="entry-content">{!! $content !!}</div>
                  </article>
               </div>
               @include('partials.app.sidebar')
               <!-- End blog sidebar -->
            </div>
         </div>
      </section>
   </div>
</div>

resources/views/partials/app/errors.blade.php
@if (isset($errors) && count($errors) > 0)
    @foreach ($errors->all() as $error)
        <div class="notification response-notification is-warning has-text-centered">
            <span class="icon">{!! icon('alert-circle') !!}</span>
            <span class="text">{{ $error }}</span>
        </div>
    @endforeach
@endif
@if (session()->has('error'))
    <div class="notification response-notification is-warning has-text-centered">
        <span class="icon">{!! icon('alert-circle') !!}</span>
        <span class="text">{{ session()->get('error') }}</span>
    </div>
@endif
@if (session()->has('success'))
    <div class="notification response-notification is-success has-text-centered">
        <span class="icon">{!! icon('info') !!}</span>
        <span class="text">{{ session()->get('success') }}</span>
    </div>
@endif

resources/views/partials/app/footer.blade.php
{{-- <footer class="footer">
    <div class="container">
        <div class="content">
            <div class="columns">
                <div class="column is-3">
                    <p class="title is-5">{{ __('app.footer.share') }}</p>
                    @foreach (['facebook', 'twitter'] as $social)
                        <p>
                            <a href="@yield($social)" rel="nofollow noopener" target="_blank">
                                <span class="icon">{!! icon($social) !!}</span>
                                <span class="text">{{ ucfirst($social) }}</span>
                            </a>
                        </p>
                    @endforeach
                </div>
                <div class="column is-3">
                    <p class="title is-5">{{ __('app.footer.latest') }}</p>
                    @foreach (getFooterArticles() as $article)
                        <p><a href="{{ $article->link }}">{{ $article->title }}</a></p>
                    @endforeach
                </div>
                <div class="column is-6">
                    <p class="title is-5">{{ __('app.footer.about') }}</p>
                    <p>{{ __('app.footer.text') }}</p>
                    <a href="{{ __('app.footer.url') }}">{{ __('app.footer.url') }}</a>
                </div>
            </div>
        </div>
    </div>
</footer> --}}
<footer id="footer" class="pt-3 pb-3 footer">
<!--Container-->
    <div class="container">
        <div class="row justify-content-between align-items-center">
            <div class="col-md-6">
                <small class="small"><span>&copy; 2020 all rights reserved - </span> <a href="#">Solutionz Creative Group </a> </small>
            </div>
            {{-- <div class="col-md-6 text-md-right">
                <ul class="list-inline small">
                <li class="list-inline-item">
                    <a href="#">Privacy Policy</a>
                </li>
                <li class="list-inline-item">
                    <a href="#">Terms of Use</a>
                </li>
                <li class="list-inline-item">
                    <a href="#">About</a>
                </li>
                <li class="list-inline-item">
                    <a href="#">Legal</a>
                </li>
                </ul>
            </div> --}}
        </div>
    </div>
    <!--End container-->
</footer>

resources/views/partials/app/headers.blade.php
@include('partials.app.errors')
    <!--Header-->
    <header class="header default">
        <div class=" left-part">
            <a class="logo scroll" href="{{ route('root') }}">
                <h2 class="mb-0 uppercase">BRONZON & DAZU</h2>
            </a>
        </div>
        <div class="right-part">
            <nav class="main-nav">
                <div class="toggle-mobile-but">
                <a href="#" class="mobile-but" >
                    <div class="lines"></div>
                </a>
                </div>
                <ul class="main-menu list-inline">
                <li><a class="scroll list-inline-item" href="{{ route('root') }}">Inicio</a></li>
                <li><a class="scroll list-inline-item" href="{{ route('root') }}#about">Biografía</a></li>
                <li><a class="scroll list-inline-item" href="{{ route('root') }}#discography">Música</a></li>
                <li><a class="scroll list-inline-item" href="{{ route('root') }}#tour">Shows</a></li>
                <li><a class="scroll list-inline-item" href="{{ route('root') }}#gallery">Galería</a></li>
                <li><a class="scroll list-inline-item" href="{{ route('root') }}#news">Noticias</a></li>
                <li><a class="scroll list-inline-item" href="{{ route('root') }}#contact">Contacto</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <!--End header-->
</section>

resources/views/partials/app/nav.blade.php
{{-- <nav class="navbar is-light">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ route('root') }}">
                <img src="{{ asset(config('settings.logo')) }}" alt="{{ config('settings.site_title') }}">
            </a>
            <div id="toggle-menu" class="navbar-burger burger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="menu" class="navbar-menu">
            <div class="navbar-start">
                @foreach (getMenu() as $p)
                    @if ($p->children->count() > 0)
                        <div class="navbar-item has-dropdown is-hoverable">
                            <div class="navbar-link">
                                <a class="navbar-item {{ active($p) }}" href="{{ $p->link }}">
                                    {{ $p->title }}
                                </a>
                            </div>
                            <div class="navbar-dropdown">
                                @foreach ($p->children as $child)
                                    <a class="navbar-item {{ active($child) }}" href="{{ $child->link }}">
                                        {{ $child->title }}
                                    </a>
                                @endforeach
                            </div>
                        </div>
                    @else
                        <a class="navbar-item" href="{{ $p->link }}">
                            {{ $p->title }}
                        </a>
                    @endif
                @endforeach
            </div>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a target="_blank" rel="noopener noreferrer" href="@yield('facebook')" class="button button-facebook">
                                <span class="icon">{!! icon('facebook') !!}</span>
                                <span>{{ __('app.buttons.share') }}</span>
                            </a>
                        </p>
                        <p class="control">
                            <a target="_blank" rel="noopener noreferrer" href="@yield('twitter')" class="button button-twitter">
                                <span class="icon">{!! icon('twitter') !!}</span>
                                <span>{{ __('app.buttons.tweet') }}</span>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav> --}}
<header class="header default">
    <div class=" left-part">
        <a class="logo scroll" href="#wrapper">
            <h2 class="mb-0 uppercase">mousiqua.</h2>
        </a>
    </div>
    <div class="right-part">
        <nav class="main-nav">
            <div class="toggle-mobile-but">
            <a href="#" class="mobile-but" >
                <div class="lines"></div>
            </a>
            </div>
            <ul class="main-menu list-inline">
            <li><a class="scroll list-inline-item" href="#wrapper">Home</a></li>
            <li><a class="scroll list-inline-item" href="#about">about</a></li>
            <li><a class="scroll list-inline-item" href="#discography">discography</a></li>
            <li><a class="scroll list-inline-item" href="#band">Band</a></li>
            <li><a class="scroll list-inline-item" href="#tour">Tours</a></li>
            <li><a class="scroll list-inline-item" href="#gallery">Gallery</a></li>
            <li><a class="scroll list-inline-item" href="#news">News</a></li>
            <li><a class="scroll list-inline-item" href="#contact">Contact</a></li>
            <li>
                <ul class="block-helper list-inline">
                    <li class="list-inline-item"><a href="#"><i class="icon-shop"></i></a></li>
                    <li class="list-inline-item"><span class="search-ico"><i class="icon-search"></i></span></li>
                </ul>
            </li>
            </ul>
        </nav>
    </div>
</header>

resources/views/partials/app/sections.blade.php
@section('title'){{ $title ?? getTitle() }}@endsection
@section('description'){{ $description ?? getDescription() }}@endsection
@section('image'){{ $image ?? getImage() }}@endsection
@section('facebook'){{ getFacebookShareLink($currentUrl ?? request()->url(), $title ?? getTitle()) }}@endsection
@section('twitter'){{ getTwitterShareLink($currentUrl ?? request()->url(), $title ?? getTitle()) }}@endsection
@section('robots'){{ $robots ?? getRobots() }}@endsection

resources/views/partials/app/sidebar.blade.php
<div class="col-lg-4">
	<div class="sidebar">
		<h3 class="sidebar-title">Categorias</h3>
		<div class="sidebar-item categories">
			<ul>
                @forelse ($categories as $category)
                    <li><a href="{{$category->link}}">{{$category->title}} <span>({!! $category->articles_count() !!})</span></a></li>
                @empty
                    <li>No hay categorias publicadas</li>
                @endforelse

			</ul>
        </div>

		<!-- End sidebar categories-->
		<h3 class="sidebar-title">Noticias Recientes</h3>
		<div class="sidebar-item recent-posts">
            @forelse ($recent_posts as $post)
                <div class="post-item clearfix">
                    <img src="{{$post->thumbnail}}" alt="{{$post->title}}">
                    <h4><a href={{$post->link}}>{{$post->title}}</a></h4>
                    <time datetime="2020-01-01">{{\Carbon\Carbon::parse($post->published_at)->format('Y-m-d')}}</time>
                </div>
            @empty
                <h4>No hay publicaciones Recientes</h4>
            @endforelse

		</div>
		<!-- End sidebar recent posts-->
	</div>
	<!-- End sidebar -->
</div>